version: 2.1

jobs:
  config_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
        fingerprints: [b1:9a:30:56:7b:e5:a9:1a:57:a8:4a:15:0c:f7:4a:58]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt playbook.yml
workflows:
  my_workflow:
    jobs:
      - config_infrastructure