version: 2.1

jobs:
  configure_aws:
    docker: 
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create inventory file
          command: |
            echo [all] > inventory
            
            aws ec2 describe-instances \
            --query "Reservations[*].Instances[*].PublicIpAddress" \
            --output text >> inventory
  config_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [8d:fc:4e:5c:3f:d1:f9:5b:dd:bb:a8:79:20:bf:cf:fd]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: stack over flow tip
          command: |
             ansible all --list-hosts
      - run:
          name: aws describe-instances
          command: |
             aws ec2 describe-instances \
             --query "Reservations[*].Instances[*].PublicIpAddress" 
      - run:
          name: export ANSIBLE_HOST_KEY_CHECKING
          command: |
            export ANSIBLE_HOST_KEY_CHECKING=False
      - run:
          name: Configure server
          command: |
            ansible-playbook playbook.yml -i inventory
workflows:
  my_workflow:
    jobs:
      - configure_aws
      - config_infrastructure:
          requires:
            - configure_aws