version: 2.1

commands:
  only_if_error:
    steps:
      - run: 
          name: Error while trying deploy!
          command: echo "Fred, Error!"

jobs:
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test
          command: |  #simulate error
            URL="https://blog.udacity333.com/"
            if curl -s --head ${URL}
            then
              return 0
            else
              return 1
            fi
      - run: 
          command: only_if_error
          name: teste
          when: on_fail
    
  config_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [8d:fc:4e:5c:3f:d1:f9:5b:dd:bb:a8:79:20:bf:cf:fd]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: stack over flow tip
          command: |
             ansible all --list-hosts
      - run:
          name: export ANSIBLE_HOST_KEY_CHECKING=False
          command: |
            export ANSIBLE_HOST_KEY_CHECKING=False
      - run:
          name: Configure server
          command: |
            ansible-playbook playbook.yml -i inventory
workflows:
  my_workflow:
    jobs:
      - config_infrastructure
      - smoke_test:
          requires:
            - config_infrastructure